language: node_js
sudo: true
dist: trusty
node_js:
  - "9.0"
  - "10.0"
  - "11.0"
  - "12.0"
install:
  - npm i -g npm
  - npm install
script:
  - npm run test
notifications:
  email:
    on_failure: change
